# Creative Item Control Plugin Config
# This plugin is designed to give full control over item data to server administrators, especially those
# with creative mode worlds or servers

toggles:
  master: true # False:
  enchantments: true # Block impossible enchants
  attributes: true # Block impossible attribute modifiers
  potions: true # Block custom potions
  playeralerts: true # Send alerts to player attempting to get the item

config:
  worlds: # Worlds in which the plugin is active
    - example
  blacklist: false # If true, above worlds config will act as a blacklist



enchantments:
  # By default, only regular enchantments and levels will be allowed.
  # Action to take when impossible enchants are found. Options:
  # LOWER - Set enchants to the highest possible value for that item
  # REMOVE - Remove enchantments from the item all-together
  # DELETE - Delete the item
  action: LOWER
  allow-incompatible: false # Whether or not to allow incompatible enchantments (Sharpness with Smite, Infinity with Mending, etc)

attributes:
  # By default, no attribute modifying items will be allowed
  # Action to take when attribute modifiers are found. Options:
  # REMOVE - Remove the attribute modifiers from the item
  # DELETE - Delete the item
  action: DELETE




