name: CreativeItemControl
version: '1.1.2'
main: net.kingidk.creativeItemControl.CreativeItemControl
api-version: '1.21'
authors: [ Kingidk ]
folia-supported: true
commands:
  cic:
    description: Main CreativeItemControl command
    usage: /cic <reload|list|store|give>
    permission-message: You do not have permission
permissions:
  cic.bypass.*:
    description: Bypass all checks
    default: op
  cic.bypass.enchantments:
    description: Bypass enchantment checks
    default: op
  cic.bypass.attributes:
    description: Bypass attribute checks
    default: op
  cic.bypass.potions:
    description: Bypass custom potion checks
    default: op
  cic.bypass.components:
    description: Bypass component checks
    default: op
  cic.admin:
    description: Admin Commands
    default: op
  cic.give:
    description: Allow giving items to self
    default: op
