name: CreativeItemControl
version: '1.0-SNAPSHOT'
main: net.kingidk.creativeItemControl.CreativeItemControl
api-version: '1.21'
authors: [ Kingidk ]
commands:
  cic:
    description: Reload CreativeItemControl config
    usage: /cic reload
    permission: creativeitemcontrol.reload
    permission-message: You do not have permission
permissions:
  cic.bypass.*:
    description: Bypass all checks
    default: op
  cic.bypass.enchantments:
    description: Bypass enchantment checks
    default: op
  cic.bypass.attributes:
    description: Bypass attribute checks
    default: op
  cic.bypass.potions:
    description: Bypass custom potion checks
    default: op